#!/bin/bash

if [ "$EUID" == 0 ]; then
    source .lib_file

    printf "Do you want to\n1 - make a new folder to share\n2 - share an existing folder\n"
    NewFolder=$(Choice_cycle)

    ShareName=$(Input_cycle "Share name" "the share name")
    FolderPath=$(Input_cycle "Folder path" "the full path of the share folder")


    if [ "${NewFolder}" == 1 ]; then
	#mkdir -p ${FolderPath}
	printf "Newfolder is 1"
    fi

    #printf "\n[${ShareName}]\n	path = ${FolderPath}\n	 read only = no" >> /etc/samba/smb.conf
    #smbcontrol all reload-config

else
    echo "Script must be run as root"
fi

exit 0
