#!/bin/bash

if [ "$EUID" == 0 ]; then

    printf "Choose your configuration\n1 - Configure as a Standalone File Server\n"\
"2 - Configure as Domain Member\n"

    ConfigReset=1
    while [ "${ConfigReset}" == 1 ]; do
	if [ -z "${ConfigMessage}" ]; then
	    ChoiceMessage=1
	elif [ "${ConfigMessage}" ]; then
	    echo "Must enter 1 or 2"
	fi

	read -p ">" ConfigChoice

	if [ "${ConfigChoice}" == 1 ] || [ "${ConfigChoice}" == 2 ]; then
	    ConfigReset=0
	fi
    done


    if [ "${ConfigChoice}" == 1 ]; then
	apt install samba

#	printf "To share a home folder of a user you must create th user in samba using:"\
#"smbpasswd -a username"

#potentially choices for configuration (read only, browsable....)

    elif [ "${ConfigChoice}" == 2 ]; then

	while [ -z "${KerberosRealm}" ]; do
	    if [ -z "${KRBMessage}" ]; then
		KRBMessage=1
	    elif [ "${KRBMessage}" ]; then
		echo "Kerberos realm must be entered"
	    fi
	    read -p "Kerberos realm must be entered:" KerberosRealm
	done

	while [ -z "${PDCIP}" ]; do
	    if [ -z "${PDCIPMessage}" ]; then
		PDCIPMessage=1
	    elif [ "${PDCIPMessage}" ]; then
		echo "IP of the primary DC must be entered"
	    fi
	    read -p "Enter the IP of the primary DC:" PDCIP
	done

	DEBIAN_FRONTEND=noninteractive apt -yq install acl attr samba samba-dsdb-modules samba-vfs-modules winbind libpam-winbind libnss-winbind libpam-krb5 krb5-config krb5-user dnsutils resolvconf

	nameservers="nameserver ${PDCIP}\nsearch ${KerberosRealm^^}\n"
	sed -i "s/nameserver ${PDCIP}//g" /etc/resolvconf/resolv.conf.d/head
	sed -i "s/search ${KerberosRealm^^}//g" /etc/resolvconf/resolv.conf.d/head
	nameservers="${nameservers}$(cat /etc/resolvconf/resolv.conf.d/head | grep -w nameserver)\n"
	printf "${nameservers}" > /etc/resolvconf/resolv.conf.d/head

	systemctl restart resolvconf

	printf "[libdefaults]\n default_realm = ${KerberosRealm^^}\ndns_lookup_realm = false\ndns_lookup_kdc = true" > /etc/krb5.conf

	cp /etc/samba/smb.conf /etc/samba/smb.conf.bckp
	cp ./.smb.conf /etc/samba/smb.conf
	smbcontrol all reload-config

	net ads join -U administrator

	passwdline=$(cat /etc/nsswitch.conf | grep -w passwd)
	groupline=$(cat /etc/nsswitch.conf | grep -w group)
	passwdlinenew="${passwdline} winbind"
	grouplinenew="${groupline} winbind"

	sed -i "s/${passwdline}/${passwdlinenew}/" /etc/nsswitch.conf
	sed -i "s/${groupline}/${grouplinenew}/" /etc/nsswitch.conf

	systemctl restart smbd nmbd winbind

    fi

else

    printf "This script must be run as root"

fi

exit 0
